/*
 * Copyright (c) Haulmont 2025. All Rights Reserved.
 * Use is subject to license terms.
 */

base {
    archivesName = 'flowset-ui-kit-starter'
}

jmix {
    entitiesEnhancing {
        enabled = false
    }
}

dependencies {
    api project(':flowset-ui-kit')

    implementation 'org.springframework.boot:spring-boot-autoconfigure'
}