/*
 * Copyright (c) Haulmont 2025. All Rights Reserved.
 * Use is subject to license terms.
 */

import com.github.spotbugs.snom.Confidence
import com.github.spotbugs.snom.Effort

buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath "io.jmix.gradle:jmix-gradle-plugin:3.0.1"
    }
}

plugins {
    id 'com.github.spotbugs' version '6.5.9' apply false
}

group = 'io.flowset.ui'

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'io.jmix'

    if (project.hasProperty('spotbugsEnabled')) {
        apply plugin: "com.github.spotbugs"
    }

    repositories {
        mavenCentral()
        maven {
            url = 'https://nexus.flowset.io/repository/public'
        }
        maven {
            url = 'https://global.repo.jmix.io/repository/public'
        }
    }

    jmix {
        bomVersion = '3.0.1'
        projectId = 'flowset-ui-kit'
    }

    group = this.group
    version = this.version

    def props = new Properties()
    buildFile.withInputStream { props.load(it) }

    java {
        withSourcesJar()
        withJavadocJar()
    }

    artifacts {
        archives sourcesJar
    }

    publishing {
        if (rootProject.hasProperty('flowsetUploadUrl')) {
            repositories {
                maven {
                    url = rootProject['flowsetUploadUrl']
                    credentials {
                        username = rootProject['flowsetUploadUser']
                        password = rootProject['flowsetUploadPassword']
                    }
                    allowInsecureProtocol = true
                }
            }
        }

        publications {
            javaMaven(MavenPublication) {
                artifactId = project.base.archivesName.get()
                from components.java
            }
        }
    }

    if (project.hasProperty('spotbugsEnabled')) {
        spotbugs {
            ignoreFailures = false
            omitVisitors = ['FindDoubleCheck']
            excludeFilter = project.file('../etc/spotbugs/spotbugs-exclude-filter.xml')
            effort = Effort.valueOf('MAX')
            reportLevel = Confidence.valueOf('MEDIUM')
        }

        spotbugsMain {
            jvmArgs = ['-Xmx1024m']

            reports {
                xml.enabled = false
                html {
                    enabled = true
                    stylesheet = 'fancy-hist.xsl'
                    outputLocation = layout.buildDirectory.file("reports/spotbugs/${project.name}.html").get().asFile
                }
            }
        }

        spotbugsTest {
            jvmArgs = ['-Xmx1024m']

            reports {
                xml.enabled = false
                html {
                    enabled = true
                    stylesheet = 'fancy-hist.xsl'
                    outputLocation = layout.buildDirectory.file("reports/spotbugs/test-${project.name}.html").get().asFile
                }
            }
        }
    }

    // remove after https://youtrack.jetbrains.com/issue/IDEA-227215 is fixed
    tasks.withType(GenerateModuleMetadata) {
        enabled = false
    }

    tasks.withType(Javadoc) {
        options.addStringOption("sourcepath", "")
        options.encoding = 'UTF-8'
        options.memberLevel = JavadocMemberLevel.PROTECTED
    }

    project.tasks.withType(JavaCompile).configureEach {
        options.compilerArgs.add("-parameters")
    }

}
